apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          args: ["-c", "max_connections=500"]
          ports:
            - name: http
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
#          lifecycle:
#            postStart:
#              exec:
#                command: [ "/bin/sh", "-c", "createdb calc -U postgres" ]
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: http
      port: 5432
      targetPort: http
