apiVersion: v1
kind: Service
metadata:
  name: calc-headless
spec:
  selector:
    app: calc
  type: ClusterIP
  clusterIP: None
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: calc
#  namespace: default
#spec:
#  selector:
#    name: calc
#  ports:
#    - protocol: TCP
#      port: 4000
#      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: calc-lb
  labels:
    app: calc
spec:
  type: LoadBalancer
  selector:
    app: calc
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 4000
